# -*- coding: utf-8 -*-
"""OECD fertility rates.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/114pwjnAz3IgvvMg8aHL0QGHpEyFLEtwH
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

df = pd.read_csv('oecd fertility rates.csv')

df

len(df['LOCATION'].unique())

new_df = df[df['LOCATION'] == 'AUS'][['TIME','Value']].rename(columns = {'Value': 'AUS'})

new_df.merge(df[df['LOCATION'] == 'AUT'][['TIME','Value']], on = 'TIME', how = 'outer').rename(columns={'Value':'AUT'})

#create more readable dataframe for fertility rates
for country in df['LOCATION'].unique()[1:]:
  temp = df[df['LOCATION'] == country][['TIME','Value']].rename(columns={'Value':country})
  new_df = new_df.merge(temp, on = 'TIME', how = 'outer')

new_df

len(new_df.columns)

#Make sure that Korea had lowest fertility rate since 2013 (Korea's fertility rate should be the last nine numbers listed here)
for i in np.arange(len(new_df.min(axis = 1))):
  print(new_df.min(axis = 1)[i])

"""# Change of rate (find countries with the fastest growing/dropping fertilty rates)"""

rate_df = pd.DataFrame()
rate = []
state = []

for country in df['LOCATION'].unique():
  rate.append(((new_df[country][60] - new_df[country][50])/10))
  state.append(country)

rate_df['Rate of change 2010-2020'] = rate
rate_df['Country'] = state

rate_df.sort_values(by='Rate of change 2010-2020', ascending = False, inplace = True, ignore_index = True)
rate_df

"""# Percent change (2010-2020)"""

change_df = pd.DataFrame()
perc = []
count = []
year2010 = []
year2020 = []

new_df

for country in df['LOCATION'].unique():
  perc.append(((new_df[country][60] - new_df[country][50])/new_df[country][50])*100)
  count.append(country)
  year2010.append(new_df[country][50])
  year2020.append(new_df[country][60])

change_df['Percent Change 2010-2020'] = perc
 change_df['Country'] = count
 change_df['2010'] = year2010
 change_df['2020'] = year2020

change_df

"""Now let's combine the population to each country."""

pop_df = pd.read_csv('oecd_populations.csv')
pop_df = pop_df[pop_df['TIME'] == 2020]

pop_df.head()

pop_df = pop_df[['LOCATION', 'Value']].reset_index()
pop_df.loc[41, 'LOCATION'] = 'OAVG'

pop_df = pop_df[['LOCATION', 'Value']].rename(columns={'LOCATION':'Country', 'Value': 'Population'})

pop_df

change_df = change_df.merge(pop_df, on = 'Country', how='inner')

names_df = pd.read_csv('country names.csv')

change_df = change_df.merge(names_df, left_on = 'Country', right_on = 'abbrev', how = 'outer')

change_df.sort_values(by='Percent Change 2010-2020', ascending = True, ignore_index = True)

#change_df.sort_values(by='name', ascending = True, inplace = True, ignore_index = True)

#change_df

filepath = Path('final oecd fertility rates.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
new_df.to_csv(filepath)

filepath = Path('perc change fertility.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
change_df.to_csv(filepath)